In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel("OLA_DataSet.xlsx")

In [4]:
pd.ExcelFile("OLA_DataSet.xlsx").sheet_names

['July', 'Sheet1', 'Sheet2']

In [5]:
df =pd.read_excel("OLA_DataSet.xlsx", sheet_name="Sheet2")

In [6]:
df.head()

    Unnamed: 0                                         Unnamed: 1
0  Prime Sedan  https://cdn-icons-png.flaticon.com/128/14183/1...
1         Bike  https://cdn-icons-png.flaticon.com/128/9983/99...
2    Prime SUV  https://cdn-icons-png.flaticon.com/128/9983/99...
3        eBike  https://cdn-icons-png.flaticon.com/128/6839/68...
4         Mini  https://cdn-icons-png.flaticon.com/128/3202/32...

In [7]:
df =pd.read_excel("OLA_DataSet.xlsx", sheet_name="Sheet1")

In [8]:
df.head()

,Date,Unnamed: 1,Unnamed: 2,Unnamed: 3,Vehicle_Type,Avg Distance,Unnamed: 6,Booking_Status,Unnamed: 8
0,Time,NaN,NaN,NaN,Prime Sedan,15.764939,NaN,Canceled by Driver,18434.0
1,Booking_ID,NaN,NaN,NaN,Bike,15.533079,NaN,Success,63967.0
2,Booking_Status,NaN,NaN,NaN,Prime SUV,15.274514,NaN,Canceled by Customer,10499.0
3,Customer_ID,NaN,NaN,NaN,eBike,15.580589,NaN,Driver Not Found,10124.0
4,Vehicle_Type,NaN,NaN,NaN,Mini,15.510102,NaN,NaN,103024.0

In [54]:
df =pd.read_excel("OLA_DataSet.xlsx", sheet_name="July")

In [55]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [56]:
df.shape

(103024, 20)

In [57]:
df.isnull().all(axis=1).sum()

0

In [11]:
list(df.columns)

['Date',
 'Time',
 'Booking_ID',
 'Booking_Status',
 'Customer_ID',
 'Vehicle_Type',
 'Pickup_Location',
 'Drop_Location',
 'V_TAT',
 'C_TAT',
 'Canceled_Rides_by_Customer',
 'Canceled_Rides_by_Driver',
 'Incomplete_Rides',
 'Incomplete_Rides_Reason',
 'Booking_Value',
 'Payment_Method',
 'Ride_Distance',
 'Driver_Ratings',
 'Customer_Rating',
 'Vehicle Images']

In [12]:
df.dtypes

Date                          datetime64[ns]
Time                                  object
Booking_ID                            object
Booking_Status                        object
Customer_ID                           object
Vehicle_Type                          object
Pickup_Location                       object
Drop_Location                         object
V_TAT                                float64
C_TAT                                float64
Canceled_Rides_by_Customer            object
Canceled_Rides_by_Driver              object
Incomplete_Rides                      object
Incomplete_Rides_Reason               object
Booking_Value                          int64
Payment_Method                        object
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
Vehicle Images                        object
dtype: object

In [13]:
df['Day_Name'] = df['Date'].dt.day_name()

In [14]:
df['Day_Name'].dtype

dtype('O')

In [15]:
df['Day_Name'].head()

0      Friday
1    Thursday
2     Tuesday
3      Monday
4     Tuesday
Name: Day_Name, dtype: object

Adjusting day_name beside time column

In [17]:
col = list(df.columns)
col.remove('Day_Name')

time_index = col.index('Time')
col.insert(time_index + 1, 'Day_Name')

df = df[col]

In [18]:
df.head()

,Date,Time,Day_Name,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,...,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,Friday,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,...,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,Thursday,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,...,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,Tuesday,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,...,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,Monday,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,...,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,Tuesday,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,...,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [19]:
df.columns

Index(['Date', 'Time', 'Day_Name', 'Booking_ID', 'Booking_Status',
       'Customer_ID', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location',
       'V_TAT', 'C_TAT', 'Canceled_Rides_by_Customer',
       'Canceled_Rides_by_Driver', 'Incomplete_Rides',
       'Incomplete_Rides_Reason', 'Booking_Value', 'Payment_Method',
       'Ride_Distance', 'Driver_Ratings', 'Customer_Rating', 'Vehicle Images'],
      dtype='object')

Droping tie column as we already have date column in datetime format, if needed we will create dax

In [20]:
df.drop(columns=['Time'], inplace=True)

In [21]:
df.head()

,Date,Day_Name,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,Friday,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,Thursday,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,Tuesday,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,Monday,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,Tuesday,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [22]:
df.isnull().sum()

Date                              0
Day_Name                          0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

In [23]:
df.duplicated().sum()

0

In [24]:
df.describe()

,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000
mean,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313
std,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957
min,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000
50%,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000
75%,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000
max,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000

In [25]:
df[['V_TAT', 'C_TAT']].isnull().sum()

V_TAT    39057
C_TAT    39057
dtype: int64

matching if both column have similar null values or not

In [26]:
df[df['V_TAT'].isnull()!=df['C_TAT'].isnull()][['V_TAT', 'C_TAT']].head()

Empty DataFrame
Columns: [V_TAT, C_TAT]
Index: []

In [27]:
df[['Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver']].isnull().sum()

Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
dtype: int64

Checking if both are ever filled together

In [28]:
df[df['Canceled_Rides_by_Customer'].notnull() & df['Canceled_Rides_by_Driver'].notnull()]

Empty DataFrame
Columns: [Date, Day_Name, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating, Vehicle Images]
Index: []

Checking Cancellation Count

In [29]:
customer_cancel_count = df['Canceled_Rides_by_Customer'].notnull().sum()
driver_cancel_count = df['Canceled_Rides_by_Driver'].notnull().sum()

customer_cancel_count, driver_cancel_count

(10499, 18434)

Checking if both are null together, it tells us that rides were not cancelled at al

In [31]:
df[df['Canceled_Rides_by_Customer'].isnull() &
    df['Canceled_Rides_by_Driver'].isnull()]

,Date,Day_Name,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
1,2024-07-25 22:20:00,Thursday,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,Tuesday,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
4,2024-07-02 09:02:00,Tuesday,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
5,2024-07-13 04:42:00,Saturday,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,NaN,NaN,No,NaN,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
6,2024-07-23 09:51:00,Tuesday,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,NaN,NaN,No,NaN,140,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,Wednesday,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,Wednesday,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,Wednesday,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,Wednesday,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,Wednesday,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

let count if both values are null we will count into 0 , if one null then we will count as 1 , for data clarification

In [32]:
df[['Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver']].notnull().sum(axis=1).value_counts()

0    74091
1    28933
dtype: int64

we take a case to undertsand about incomplete rides, we will check it by confirming if v_tat and c_tat are null then the incomplete rides should also show null.

In [33]:
case1 = df[df['V_TAT'].isnull() & df['C_TAT'].isnull()][['V_TAT', 'C_TAT', 'Incomplete_Rides']]

case1['Incomplete_Rides'].value_counts(dropna=False)

NaN    39057
Name: Incomplete_Rides, dtype: int64

now to check for every no null value in v_tat and c_tat m, how many we have no and yes we get in incomplete rides.

In [34]:
case2 = df[df['V_TAT'].notnull() & df['C_TAT'].notnull()][['V_TAT', 'C_TAT', 'Incomplete_Rides']]

case2['Incomplete_Rides'].value_counts(dropna=False)

No     60041
Yes     3926
Name: Incomplete_Rides, dtype: int64

every incomplete ride with yes must have a reson let check if any have nulll values or not

In [35]:
df[
    (df['Incomplete_Rides']== "Yes") &
    (df['Incomplete_Rides_Reason'].isnull())
].shape[0]

0

In [36]:
df.groupby('Incomplete_Rides')['Incomplete_Rides_Reason'] \
.apply(lambda x: x.notnull().mean())

Incomplete_Rides
No     0.0
Yes    1.0
Name: Incomplete_Rides_Reason, dtype: float64

In [37]:
df.isnull().sum()

Date                              0
Day_Name                          0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

case 1 , if incomplete ride is null then payment method should be null

In [38]:
df[
    (df['Incomplete_Rides'].isnull()) &
    (df['Payment_Method'].notnull())
].shape[0]

0

case2 , id incmpplete ride is null then ride distance should be 0

In [39]:
df[
    (df['Incomplete_Rides'].isnull()) &
    (df['Ride_Distance'] != 0)
].shape[0]

0

In [40]:
df.groupby('Incomplete_Rides')['Ride_Distance'].describe()

                    count       mean        std  min   25%   50%   75%   max
Incomplete_Rides
No                60041.0  22.819940  14.239762  1.0  10.0  21.0  35.0  49.0
Yes                3926.0  23.375191  14.275776  1.0  11.0  22.0  36.0  49.0

In [41]:
df[
    (df['Incomplete_Rides'] == 'Yes') &
    (df['Ride_Distance'] <0)
].shape[0]

0

In [42]:
df[
    (df['Incomplete_Rides'] == 'Yes') &
    (
        df['Driver_Ratings'].notnull() |
        df['Customer_Rating'].notnull()
    )
].shape[0]

3926

In [43]:
df[
    (df['Incomplete_Rides'] == 'Yes') &
    (
        df['Driver_Ratings'].notnull() |
        df['Customer_Rating'].notnull()
    )
][['Incomplete_Rides', 'Driver_Ratings', 'Customer_Rating']]

       Incomplete_Rides  Driver_Ratings  Customer_Rating
38                  Yes             3.1              3.5
49                  Yes             4.1              4.6
70                  Yes             4.1              4.9
93                  Yes             4.7              4.8
101                 Yes             3.2              3.2
...                 ...             ...              ...
102859              Yes             4.7              3.3
102870              Yes             4.3              4.9
102973              Yes             4.4              4.5
102978              Yes             3.6              4.3
103011              Yes             3.8              4.2

[3926 rows x 3 columns]

In [44]:
df[df['Incomplete_Rides'] == 'Yes'][['Driver_Ratings', 'Customer_Rating']].notnull().mean()

Driver_Ratings     1.0
Customer_Rating    1.0
dtype: float64

We checked that for any incomplete ride=yes , customer and driver ratings are availaible , it meand data is not worng, platform like ola allows give rating even if the ride did not complete

SQL SERVER CONNECTION

In [45]:
# SQL Server connectivity
import pyodbc
from sqlalchemy import create_engine

In [47]:
import pandas as pd
import pyodbc
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://@localhost/OLA RIDE_ANALYTICS"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

pd.read_sql("SELECT DB_NAME() AS CurrentDB", engine)

            CurrentDB
0  OLA RIDE_ANALYTICS

In [48]:
pd.read_sql("""
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
""", engine)

Empty DataFrame
Columns: [TABLE_NAME]
Index: []

In [49]:
df.to_sql(
    name="ola_rides",         
    con=engine,
    if_exists="replace",       
    index=False
)

-1

In [51]:
pd.read_sql("""
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES
""", engine)

  TABLE_NAME
0  ola_rides

In [52]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM ola_rides",
    engine
)

   total_rows
0      103024

In [53]:
pd.read_sql(
    "SELECT TOP 5 * FROM ola_rides",
    engine
)

,Date,Day_Name,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,Friday,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,None,Personal & Car related issue,None,None,444,None,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,Thursday,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,None,None,No,None,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,Tuesday,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,None,None,No,None,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,Monday,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,None,None,None,384,None,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,Tuesday,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,None,None,No,None,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...